##### The University of Melbourne, School of Computing and Information Systems
# COMP30027 Machine Learning, 2022 Semester 1

## Assignment 2: Sentiment Classification of Tweets

This is a sample code to assist you with vectorising the 'Train' dataset for your assignment 2.

First we read the CSV datafiles (Train and Test).

In [368]:
# This code block partitions Train.csv for holdout
# If a code block doen't work simply run all and it should reset variables
# kernel used is base (Python 3.9.7)
# Code used has been adapted from practicals

import pandas as pd

train_data_full = pd.read_csv("Train.csv", sep=',')

trainrows = int(0.7*len(train_data_full))
testrows = int(0.3*len(train_data_full))+1

print(len(train_data_full),trainrows,testrows)

train_data = pd.read_csv("Train.csv", sep=',', nrows=trainrows)

trainevaldata = pd.read_csv("Train.csv", sep=',')
evaldata = trainevaldata.iloc[trainrows:trainrows+testrows, :-1]
evalanswers = trainevaldata.iloc[trainrows:trainrows+testrows, [1,-1]]

test_data = pd.read_csv("Test.csv", sep=',', nrows=5)

display(train_data)
display(evaldata)
display(evalanswers)

#print("\n")

print(evalanswers.iloc[2,-1])


21802 15261 6541


Unnamed: 0                  id  \
0               2  805582613687713000   
1               3  637480203497832000   
2               4  641096279930507000   
3               5  625730917647126000   
4               6  633292370906230000   
...           ...                 ...   
15256       19596  625891517274701000   
15257       19597  641364140947148000   
15258       19598  636993524911763000   
15259       19599  620722821870829000   
15260       19601  681419250217664000   

                                                    text sentiment  
0       doctors hit campaign trail as race to medical...   neutral  
1       is anybody going to the radio station tomorro...  positive  
2       i just found out naruto didn't become the 5th...   neutral  
3       "prince george reservist who died saturday ju...   neutral  
4       season in the sun versi nirvana rancak gak..s...  positive  
...                                                  ...       ...  
15256   "#cubs beat #rockies 9-8 on kris bryant's wal...   neutral  
15257   dr. roseen will be in h3 tomorrow at 12:30p p...   neutral  
15258   "@ happy amelemshaty hahahahhahahaha, kan hyb...   neutral  
15259   "@michael22418062 watchman was the 1st draft ...   neutral  
15260   "tony blair's labour may have seemed 'moderat...   neutral  

[15261 rows x 4 columns]

Unnamed: 0                  id  \
15261       19602  679602563478614000   
15262       19603  637460573811277000   
15263       19604  802014331235921000   
15264       19605  802161345294647000   
15265       19606  802380028549828000   
...           ...                 ...   
21797       27896  805677750363095000   
21798       27897  637854813930196000   
21799       27898  802374277047656000   
21800       27899  640441306494296000   
21801       27900  638666306015789000   

                                                    text  
15261   gardai fear a split in the ira and sinn fein?...  
15262   psa i am stealing shawn tomorrow night. he wi...  
15263   fastpowerpunch movesbowieaction notfastest #i...  
15264   @paulboy the make-up free=fresh face look- so...  
15265   electing to ‚äòopt out‚äù of obamacare : john...  
...                                                  ...  
21797  @hrtablaze the beginning of a dictatorship is ...  
21798       son idc anymore. i'm going by shawn tomorrow  
21799  but remember the clinton foundation?? https://...  
21800  press: "r u worried murray dominated his 3rd r...  
21801  @rinashah i have been using moto g 2nd gen for...  

[6541 rows x 3 columns]

id sentiment
15261  679602563478614000  negative
15262  637460573811277000   neutral
15263  802014331235921000  negative
15264  802161345294647000  positive
15265  802380028549828000   neutral
...                   ...       ...
21797  805677750363095000  negative
21798  637854813930196000   neutral
21799  802374277047656000   neutral
21800  640441306494296000   neutral
21801  638666306015789000  positive

[6541 rows x 2 columns]

negative


In [369]:
# This code block extracts the features and class labels

#separating instance and label for Train
X_train_raw = [x[0] for x in train_data[['text']].values]
Y_train = [x[0] for x in train_data[['sentiment']].values]

#check the result
print("Train length:",len(X_train_raw))

#separating instance and label for Test
#X_test_raw = [x[0] for x in test_data[['text']].values]
X_test_raw = [x[0] for x in evaldata[['text']].values]
Y_test = [x[0] for x in evalanswers[['sentiment']].values]

#check the result
print("Test length:",len(X_test_raw))

Train length: 15261
Test length: 6541


In [362]:
# This code block is for playing around with BoW and tfidf accuracies

# BoW vs tfidf

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.feature_extraction.text import CountVectorizer

BoW_vectorizer = CountVectorizer(ngram_range=(1,1), strip_accents='ascii', lowercase=True)

#Build the feature set (vocabulary) and vectorise the Train dataset using BoW
X_train_BoW = BoW_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_BoW = BoW_vectorizer.transform(X_test_raw)



from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)




models = [#GaussianNB(),
          #MultinomialNB(),
          DecisionTreeClassifier(max_depth=1),
          #KNeighborsClassifier(n_neighbors=200),
          #DecisionTreeClassifier(max_depth=None),
          #LogisticRegression(max_iter = 500),
          #SVC(kernel='rbf', gamma=0.7),
          #SVC(kernel='linear')
          ]
titles = [#'GNB',
          #'MNB',
          'one-r',
          #'5-nearest neighbour',
          #'Decision Tree',
          #'Logistic Regression',
          #'SVM with a cubic kernel',
          #'SVM with an RBF kernel'
          ]


Xs = [(X_train_BoW, X_test_BoW), (X_train_tfidf, X_test_tfidf)]
X_names = ['BoW', 'tfidf']
for title, model in zip(titles, models):
    print('\n=========',title)
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        accuracy =  accuracy_score(Y_test, y_test_predict)
        print(X_name, 'accuracy is:',  accuracy)




========= one-r
BoW accuracy is: 0.6462314630790399
tfidf accuracy is: 0.6460785812566886


In [370]:
# One R

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)


from sklearn.model_selection import cross_val_score
import numpy as np

models = [DecisionTreeClassifier(max_depth=1),]
titles = ['one-r']

XX = [x[0] for x in train_data_full[['text']].values]
yy = [x[0] for x in train_data_full[['sentiment']].values]
XX = tfidf_vectorizer.fit_transform(XX)

# Holdout score
Xs = [(X_train_tfidf, X_test_tfidf)]
X_names = ['tfidf']
for title, model in zip(titles, models):
    print('\n=========',title)
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        accuracy =  accuracy_score(Y_test, y_test_predict)
        print(X_name, 'accuracy is:',  accuracy)

# Cross validation score
for title, model in zip(titles, models):
    acc = np.mean(cross_val_score(model, XX, yy, cv=5))
    print(title, "Accuracy:",acc)


========= one-r
tfidf accuracy is: 0.6460785812566886
one-r Accuracy: 0.5852214898947931


In [365]:
# This code block is for playing around with BoW

# BoW

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


models = [#GaussianNB(),
          MultinomialNB(),
          #DecisionTreeClassifier(max_depth=1),
          #KNeighborsClassifier(n_neighbors=20),
          #DecisionTreeClassifier(max_depth=10),
          #LogisticRegression(max_iter = 1000),
          #SVC(kernel='rbf', gamma=0.7),
          #SVC(kernel='linear')
          ]
titles = [#'GNB',
          'MNB',
          #'one-r',
          #'5-nearest neighbour',
          #'Decision Tree',
          #'Logistic Regression',
          #'SVM with a rbf kernel',
          #'SVM with an linear kernel'
          ]

k = 1000

for k in [10,50,100,200,500,750,1000]:
    print('\n--------------------------------------- K = ', k,'------------------------------')
    x2 = SelectKBest(chi2, k=k)
    x2.fit(X_train_BoW,Y_train)
    X_train_x2 = x2.transform(X_train_BoW)
    X_test_x2 = x2.transform(X_test_BoW)


    Xs = [(X_train_BoW, X_test_BoW),(X_train_x2, X_test_x2)]
    X_names = ['BoW', 'x2']
    for title, model in zip(titles, models):
        print('\n=========',title, '(with k=',k,'features): ')
        for X_name, X in zip(X_names, Xs):
            X_train_t, X_test_t = X
            model.fit(X_train_t, Y_train)
            y_test_predict = model.predict(X_test_t)
            accuracy =  accuracy_score(Y_test, y_test_predict)
            print(X_name, 'accuracy is:',  accuracy)

    
    #(X_train_BoW, X_test_BoW),
    #'BoW',

    



--------------------------------------- K =  10 ------------------------------

========= MNB (with k= 10 features): 
BoW accuracy is: 0.66243693624828
x2 accuracy is: 0.6526524996177955

--------------------------------------- K =  50 ------------------------------

========= MNB (with k= 50 features): 
BoW accuracy is: 0.66243693624828
x2 accuracy is: 0.6563216633542271

--------------------------------------- K =  100 ------------------------------

========= MNB (with k= 100 features): 
BoW accuracy is: 0.66243693624828
x2 accuracy is: 0.6518880905060388

--------------------------------------- K =  200 ------------------------------

========= MNB (with k= 200 features): 
BoW accuracy is: 0.66243693624828
x2 accuracy is: 0.6479131631249044

--------------------------------------- K =  500 ------------------------------

========= MNB (with k= 500 features): 
BoW accuracy is: 0.66243693624828
x2 accuracy is: 0.6228405442592876

--------------------------------------- K =  750 ----

In [366]:
# This code block is for playing around with tfidf

# tfidf

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


models = [#GaussianNB(),
          #MultinomialNB(),
          #DecisionTreeClassifier(max_depth=1),
          KNeighborsClassifier(n_neighbors=20),
          #DecisionTreeClassifier(),
          #LogisticRegression(max_iter = 1000),
          #SVC(kernel='rbf', gamma=0.7),
          #SVC(kernel='linear')
          ]
titles = [#'GNB',
          #'MNB',
          #'one-r',
          '5-nearest neighbour',
          #'Decision Tree',
          #'Logistic Regression',
          #'SVM with a rbf kernel',
          #'SVM with an linear kernel'
          ]

k = 1000

for k in [10,50,100,200,500,750,1000]:
    print('\n--------------------------------------- K = ', k,'------------------------------')
    x2 = SelectKBest(chi2, k=k)
    x2.fit(X_train_tfidf,Y_train)
    X_train_x2 = x2.transform(X_train_tfidf)
    X_test_x2 = x2.transform(X_test_tfidf)


    #mi = SelectKBest(score_func=mutual_info_classif, k=k)
    #mi.fit(X_train_tfidf,Y_train)
    #X_train_mi = mi.transform(X_train_tfidf)
    #X_test_mi = mi.transform(X_test_tfidf)


    Xs = [(X_train_tfidf, X_test_tfidf), (X_train_x2, X_test_x2)]
    X_names = ['tfidf', 'x2']
    for title, model in zip(titles, models):
        print('\n=========',title, '(with k=',k,'features): ')
        for X_name, X in zip(X_names, Xs):
            X_train_t, X_test_t = X
            model.fit(X_train_t, Y_train)
            y_test_predict = model.predict(X_test_t)
            accuracy =  accuracy_score(Y_test, y_test_predict)
            print(X_name, 'accuracy is:',  accuracy)

    



--------------------------------------- K =  10 ------------------------------

========= 5-nearest neighbour (with k= 10 features): 
tfidf accuracy is: 0.640574835652041
x2 accuracy is: 0.6517352086836875

--------------------------------------- K =  50 ------------------------------

========= 5-nearest neighbour (with k= 50 features): 
tfidf accuracy is: 0.640574835652041
x2 accuracy is: 0.6554043724201193

--------------------------------------- K =  100 ------------------------------

========= 5-nearest neighbour (with k= 100 features): 
tfidf accuracy is: 0.640574835652041
x2 accuracy is: 0.6602965907353615

--------------------------------------- K =  200 ------------------------------

========= 5-nearest neighbour (with k= 200 features): 
tfidf accuracy is: 0.640574835652041
x2 accuracy is: 0.6618254089588748

--------------------------------------- K =  500 ------------------------------

========= 5-nearest neighbour (with k= 500 features): 
tfidf accuracy is: 0.6405748356

In [371]:
# MultinomialNB BoW

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.feature_extraction.text import CountVectorizer

BoW_vectorizer = CountVectorizer(ngram_range=(1,2), strip_accents='ascii', lowercase=False)

#Build the feature set (vocabulary) and vectorise the Train dataset using BoW
X_train_BoW = BoW_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_BoW = BoW_vectorizer.transform(X_test_raw)

models = [MultinomialNB(alpha=1,fit_prior=True)]
titles = ['MNB']

mnbpredictions = []

Xs = [(X_train_BoW, X_test_BoW)]
X_names = ['BoW']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        #print(y_test_predict)
        mnbpredictions = y_test_predict
        accuracy =  accuracy_score(Y_test, y_test_predict)
        print(title,X_name, 'accuracy is:',  accuracy)
        print(confusion_matrix(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))
        print(classification_report(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))

print(mnbpredictions)

from sklearn.model_selection import cross_val_score
import numpy as np

XX = [x[0] for x in train_data_full[['text']].values]
yy = [x[0] for x in train_data_full[['sentiment']].values]
XX = BoW_vectorizer.fit_transform(XX)


for title, model in zip(titles, models):
    acc = np.mean(cross_val_score(model, XX, yy, cv=5))
    print(title, "Accuracy:",acc)

    


MNB BoW accuracy is: 0.6708454364776029
[[ 114  754   27]
 [ 114 3769  384]
 [   5  869  505]]
              precision    recall  f1-score   support

    negative       0.49      0.13      0.20       895
     neutral       0.70      0.88      0.78      4267
    positive       0.55      0.37      0.44      1379

    accuracy                           0.67      6541
   macro avg       0.58      0.46      0.47      6541
weighted avg       0.64      0.67      0.63      6541

['neutral' 'neutral' 'neutral' ... 'neutral' 'neutral' 'neutral']
MNB Accuracy: 0.635308205129284


In [336]:
# Logistic regression tfidf

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)

models = [LogisticRegression(max_iter = 1000,multi_class='multinomial',solver='saga',C=1,penalty='l1')]
titles = ['Logistic Regression',]

logisticpredictions = []

Xs = [(X_train_tfidf, X_test_tfidf)]
X_names = ['tfidf']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        logisticpredictions = y_test_predict
        accuracy =  accuracy_score(Y_test, y_test_predict)
        print(title,X_name, 'accuracy is:',  accuracy)
        print(confusion_matrix(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))
        print(classification_report(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))

print(logisticpredictions)

from sklearn.model_selection import cross_val_score
import numpy as np

XX = [x[0] for x in train_data_full[['text']].values]
yy = [x[0] for x in train_data_full[['sentiment']].values]
XX = tfidf_vectorizer.fit_transform(XX)


for title, model in zip(titles, models):
    acc = np.mean(cross_val_score(model, XX, yy, cv=5))
    print(title, "Accuracy:",acc)


Logistic Regression tfidf accuracy is: 0.6656474545176578
[[ 293  554   48]
 [ 342 3365  560]
 [  19  664  696]]
              precision    recall  f1-score   support

    negative       0.45      0.33      0.38       895
     neutral       0.73      0.79      0.76      4267
    positive       0.53      0.50      0.52      1379

    accuracy                           0.67      6541
   macro avg       0.57      0.54      0.55      6541
weighted avg       0.65      0.67      0.66      6541

['neutral' 'positive' 'neutral' ... 'neutral' 'neutral' 'positive']
Logistic Regression Accuracy: 0.6659012956795956


In [338]:
# SVM tfidf

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)

models = [SVC(kernel='sigmoid',decision_function_shape='ovo',C=1,gamma='scale')]
titles = ['SVM with an linear kernel']

svmpredictions = []

Xs = [(X_train_tfidf, X_test_tfidf)]
X_names = ['tfidf']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        svmpredictions = y_test_predict
        accuracy =  accuracy_score(Y_test, y_test_predict)
        print(title,X_name, 'accuracy is:',  accuracy)
        print(confusion_matrix(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))
        print(classification_report(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))

print(svmpredictions)

from sklearn.model_selection import cross_val_score
import numpy as np

XX = [x[0] for x in train_data_full[['text']].values]
yy = [x[0] for x in train_data_full[['sentiment']].values]
XX = tfidf_vectorizer.fit_transform(XX)


for title, model in zip(titles, models):
    acc = np.mean(cross_val_score(model, XX, yy, cv=5))
    print(title, "Accuracy:",acc)


SVM with an linear kernel tfidf accuracy is: 0.6696223818987922
[[ 292  565   38]
 [ 337 3418  512]
 [  27  682  670]]
              precision    recall  f1-score   support

    negative       0.45      0.33      0.38       895
     neutral       0.73      0.80      0.77      4267
    positive       0.55      0.49      0.52      1379

    accuracy                           0.67      6541
   macro avg       0.58      0.54      0.55      6541
weighted avg       0.65      0.67      0.66      6541

['neutral' 'positive' 'neutral' ... 'neutral' 'neutral' 'positive']
SVM with an linear kernel Accuracy: 0.671084182358646


In [339]:
# KNN chisq tfidf

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)

models = [KNeighborsClassifier(n_neighbors=100, weights='distance')]
titles = ['k-nearest neighbour']



for f in [300]:
    print('\n--------------------------------------- f = ', f,'------------------------------')
    x2 = SelectKBest(chi2, k=f)
    x2.fit(X_train_tfidf,Y_train)
    X_train_x2 = x2.transform(X_train_tfidf)
    X_test_x2 = x2.transform(X_test_tfidf)

    knnpredictions = []

    Xs = [(X_train_x2, X_test_x2)]
    X_names = ['x2']
    for title, model in zip(titles, models):
        print('\n=========',title, '(with f=',f,'features): ')
        for X_name, X in zip(X_names, Xs):
            X_train_t, X_test_t = X
            model.fit(X_train_t, Y_train)
            y_test_predict = model.predict(X_test_t)
            knnpredictions = y_test_predict
            accuracy =  accuracy_score(Y_test, y_test_predict)
            print(X_name, 'accuracy is:',  accuracy)
            print(confusion_matrix(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))
            print(classification_report(Y_test, y_test_predict, labels=["negative", "neutral", "positive"]))

print(knnpredictions)

from sklearn.model_selection import cross_val_score
import numpy as np

XX = [x[0] for x in train_data_full[['text']].values]
yy = [x[0] for x in train_data_full[['sentiment']].values]
XX = tfidf_vectorizer.fit_transform(XX)


for title, model in zip(titles, models):
    acc = np.mean(cross_val_score(model, XX, yy, cv=5))
    print(title, "Accuracy:",acc)



--------------------------------------- f =  300 ------------------------------

========= k-nearest neighbour (with f= 300 features): 
x2 accuracy is: 0.6602965907353615
[[  22  851   22]
 [  47 4018  202]
 [   8 1092  279]]
              precision    recall  f1-score   support

    negative       0.29      0.02      0.05       895
     neutral       0.67      0.94      0.79      4267
    positive       0.55      0.20      0.30      1379

    accuracy                           0.66      6541
   macro avg       0.50      0.39      0.38      6541
weighted avg       0.60      0.66      0.58      6541

['neutral' 'neutral' 'neutral' ... 'neutral' 'neutral' 'positive']
k-nearest neighbour Accuracy: 0.6241621945139255


In [345]:
# Combining all 4 classifiers

from collections import defaultdict

finalpredict = []
for i in range(len(svmpredictions)):
    predictcombine = defaultdict(int)
    predictcombine[svmpredictions[i]]+=1
    predictcombine[mnbpredictions[i]]+=1
    predictcombine[logisticpredictions[i]]+=1
    predictcombine[knnpredictions[i]]+=1
    count = 0
    final = " "
    for key,value in predictcombine.items():
        if value > count:
            count = value
            final = key
    finalpredict.append(final)

#print(predictcombine)
#print(finalpredict)
accuracy =  accuracy_score(Y_test, finalpredict)
print('Total accuracy is:',  accuracy)


Total accuracy is: 0.6800183458186821


In [367]:
# This code block is for generating kaggle output
# copied all the code here for ease of access 
# simply clicking run will make kaggle csv prediction file

import pandas as pd

train_data_full = pd.read_csv("Train.csv", sep=',')

trainrows = int(0.7*len(train_data_full))

train_data = pd.read_csv("Train.csv", sep=',', nrows=trainrows)


test_data = pd.read_csv("Test.csv", sep=',')

#separating instance and label for Train
X_train_raw = [x[0] for x in train_data[['text']].values]
Y_train = [x[0] for x in train_data[['sentiment']].values]

#check the result
print("Train length:",len(X_train_raw))

#separating instance and label for Test
X_test_raw = [x[0] for x in test_data[['text']].values]

#check the result
print("Test length:",len(X_test_raw))

# MultinomialNB BoW

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.feature_extraction.text import CountVectorizer

BoW_vectorizer = CountVectorizer(ngram_range=(1,2), strip_accents='ascii', lowercase=False)

#Build the feature set (vocabulary) and vectorise the Train dataset using BoW
X_train_BoW = BoW_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_BoW = BoW_vectorizer.transform(X_test_raw)

models = [MultinomialNB(alpha=1,fit_prior=True)]
titles = ['MNB']

mnbpredictions = []

Xs = [(X_train_BoW, X_test_BoW)]
X_names = ['BoW']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        #print(y_test_predict)
        mnbpredictions = y_test_predict


print(mnbpredictions)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(strip_accents='ascii', ngram_range=(1,1), lowercase=True)

#Build the feature set (vocabulary) and vectorise the Tarin dataset using TFIDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_raw)

#Use the feature set (vocabulary) from Train to vectorise the Test dataset 
X_test_tfidf = tfidf_vectorizer.transform(X_test_raw)

models = [LogisticRegression(max_iter = 1000,multi_class='multinomial',solver='saga',C=1,penalty='l1')]
titles = ['Logistic Regression',]

logisticpredictions = []

Xs = [(X_train_tfidf, X_test_tfidf)]
X_names = ['tfidf']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        logisticpredictions = y_test_predict

print(logisticpredictions)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC


svmpredictions = []

Xs = [(X_train_tfidf, X_test_tfidf)]
X_names = ['tfidf']
for title, model in zip(titles, models):
    for X_name, X in zip(X_names, Xs):
        X_train_t, X_test_t = X
        model.fit(X_train_t, Y_train)
        y_test_predict = model.predict(X_test_t)
        svmpredictions = y_test_predict


print(svmpredictions)

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


models = [KNeighborsClassifier(n_neighbors=100, weights='distance')]
titles = ['k-nearest neighbour']


for f in [300]:
    
    x2 = SelectKBest(chi2, k=f)
    x2.fit(X_train_tfidf,Y_train)
    X_train_x2 = x2.transform(X_train_tfidf)
    X_test_x2 = x2.transform(X_test_tfidf)

    knnpredictions = []

    Xs = [(X_train_x2, X_test_x2)]
    X_names = ['x2']
    for title, model in zip(titles, models):
        
        for X_name, X in zip(X_names, Xs):
            X_train_t, X_test_t = X
            model.fit(X_train_t, Y_train)
            y_test_predict = model.predict(X_test_t)
            knnpredictions = y_test_predict


print(knnpredictions)

from collections import defaultdict

finalpredict = []
for i in range(len(svmpredictions)):
    predictcombine = defaultdict(int)
    predictcombine[svmpredictions[i]]+=1
    predictcombine[mnbpredictions[i]]+=1
    predictcombine[logisticpredictions[i]]+=1
    #predictcombine[knnpredictions[i]]+=1
    count = 0
    final = " "
    for key,value in predictcombine.items():
        if value > count:
            count = value
            final = key
    finalpredict.append(final)

    
import csv  

header = ['id','sentiment']

with open('1170385.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)

    writer.writerow(header)

    for i in range(len(test_data)):
        data = []
        data.append(test_data.iloc[i,0])
        data.append(finalpredict[i])
        writer.writerow(data)

Train length: 15261
Test length: 6099
['neutral' 'neutral' 'neutral' ... 'neutral' 'neutral' 'negative']
['neutral' 'neutral' 'neutral' ... 'neutral' 'positive' 'negative']
['neutral' 'neutral' 'neutral' ... 'neutral' 'positive' 'negative']
['positive' 'neutral' 'neutral' ... 'neutral' 'neutral' 'neutral']
